### ISSUE TITLE
Deploy on GitHub Pages

### ISSUE THREAD

**Issue by vsoch** [opencontainers/org#18]
When folks are ready, by going to Settings -> Github Pages --> deploy from the docs folder, the web interface should render at http://opencontainers.github.io/org. I'm guessing others want to do more changes before this happens?

**Comment by mikebrow** [comment]
I'm good with publishing @caniszczyk ^ :-)

**Comment by caniszczyk** [comment]
your wish is my command, I enabled the setting

**Comment by vsoch** [comment]
Beautiful! https://opencontainers.github.io/org/

Can we share it with others? Do you want me to?
