### ISSUE TITLE
Create SECURITY.md

### ISSUE THREAD

**Issue by caniszczyk** [opencontainers/org#22]
move this https://github.com/opencontainers/org/tree/master/security/README.md

to SECURITY.md

**Comment by vbatts** [comment]
how come?

**Comment by vbatts** [comment]
i don't remember the conversation here. I'm inclined to close this issue.

**Comment by amye** [comment]
My recollection is that it then ties in with the security tab for Github:
https://help.github.com/en/github/managing-security-vulnerabilities/adding-a-security-policy-to-your-repository

**Comment by vbatts** [comment]
@amye hrm. We had that to begin with, but it was before github has this feature. We had mad it a directory since we expected more to be added to it for processes, but that has not happened. Maybe I can switch it back without much issue
