### ISSUE TITLE
Point other OCI projects to this common org data

### ISSUE THREAD

**Issue by vbatts** [opencontainers/org#3]
- [ ] image-spec https://github.com/opencontainers/image-spec#weekly-call
 - [ ] runtime-spec https://github.com/opencontainers/runtime-spec#meetings
 - [ ] runc https://github.com/opencontainers/runc/#security
 - [ ] runtime-tools https://github.com/opencontainers/runtime-tools
 - [ ] image-tools https://github.com/opencontainers/image-tools
 - [ ] go-digest https://github.com/opencontainers/go-digest#reporting-security-issues
 - [ ] selinux https://github.com/opencontainers/selinux
 - [ ] tob https://github.com/opencontainers/tob/blob/master/code-of-conduct.md
 - [ ] project-template https://github.com/opencontainers/project-template

**Comment by vsoch** [comment]
I'll update the code of conduct links for the following (copied so I have write). I can't tell if the links to specific sections are relevant (for example, runtime-spec link to "Meetings" doesn't seem salient to data in org) so I'll assume we are talking about the code of conduct.

 * [x]  image-spec https://github.com/opencontainers/image-spec#weekly-call
 * [x]  runtime-spec https://github.com/opencontainers/runtime-spec#meetings
 * [x]  https://github.com/opencontainers/distribution-spec/pull/57

 * [ ]  runc https://github.com/opencontainers/runc/#security
 * [ ]  runtime-tools https://github.com/opencontainers/runtime-tools
 * [ ]  image-tools https://github.com/opencontainers/image-tools
 * [ ]  go-digest https://github.com/opencontainers/go-digest#reporting-security-issues
 * [ ]  selinux https://github.com/opencontainers/selinux
 * [ ]  tob https://github.com/opencontainers/tob/blob/master/code-of-conduct.md
 * [ ]  project-template https://github.com/opencontainers/project-template

**Comment by vbatts** [comment]
On 26/02/19 10:27 -0800, Vanessasaurus wrote:
>I'll update the code of conduct links for the following (copied so I have write). I can't tell if the links to specific sections are relevant (for example, runtime-spec link to "Meetings" doesn't seem salient to data in org) so I'll assume we are talking about the code of conduct.
>
> * [x]  image-spec https://github.com/opencontainers/image-spec#weekly-call
> * [x]  runtime-spec https://github.com/opencontainers/runtime-spec#meetings
> * [x]  https://github.com/opencontainers/distribution-spec/pull/57
>
> * [ ]  runc https://github.com/opencontainers/runc/#security
> * [ ]  runtime-tools https://github.com/opencontainers/runtime-tools
> * [ ]  image-tools https://github.com/opencontainers/image-tools
> * [ ]  go-digest https://github.com/opencontainers/go-digest#reporting-security-issues
> * [ ]  selinux https://github.com/opencontainers/selinux
> * [ ]  tob https://github.com/opencontainers/tob/blob/master/code-of-conduct.md
> * [ ]  project-template https://github.com/opencontainers/project-template

Meetings is since all projects use the same URL and currently the same
schedule. (and worse, some of the meeting times listed on the various
projects aren't all consistent)

**Comment by vsoch** [comment]
Let me know if there are consistent chunks that I should write for specific sections (e.g., meetings). Since the repo here has security and code of conduct, I'll look across all the repos above for those things (and point to here)!

**Comment by vbatts** [comment]
Basically, when we first started, we only had a "specs" repo which became
"runtime-spec". It was canonical for the org, and then copy-pasta happened.
Part of this /org is to clean that up and unify it.

**Comment by vsoch** [comment]
Understood - in that case updating with links for all roads to point to Rome (org) should do the trick.

**Comment by vsoch** [comment]
@vbatts I don't have the full history / background to update the templates perfectly, but above I've gone through and created consistent links to shared security and code of conduct docs here! Note that both paths won't exist until the PR is merged.

**Comment by vbatts** [comment]
this is for the most part done.
