### ISSUE TITLE
Consider renaming this project to .github

### ISSUE THREAD

**Issue by caniszczyk** [opencontainers/org#7]
https://github.blog/changelog/2019-02-21-organization-wide-community-health-files/

**Comment by vbatts** [comment]
neat. maybe later. @vsoch has been experimenting in her PRs

**Comment by vbatts** [comment]
I'm going to close this for now though.

**Comment by vsoch** [comment]
This is super cool! I knew about the .github folder, but I wasn't aware of doing the same with a repository name. The one potential issue is that if this winds up serving GitHub pages, I wonder if this repository (or any repo that starts with a dot - I didn't know it was allowed) can still serve pages. It would be along the lines of `opencontainers.github.io/.github` which sounds kind of weird.

I think for now, assuming there will be GitHub pages, it's logical to keep the name as "org." However, if this .github repository could add this value for the other repos, We should consider separating the Code of Conduct, security, etc. from the "getting started with contributions" GitHub pages.

How about - let's move forward with our current work to add the org GitHub pages, and if we decide to go for the .github naming, we can do the switch and see if pages breaks. I'm actually quite curious about this, and it wouldn't hurt as long as we don't publicly announce the site. Worst case scenario, we create a second repository for either Github pages or the organizational docs.

**Comment by vsoch** [comment]
okay so I tried it out - works as expected! Here is a .github repo:

https://github.com/singularityhub/.github

And notice the index.html - there isn't anything interesting there (although if GItHub is making this a thing they really should automatically render a beautiful interface for us) so I just added an index.html to redirect. So try going to:

https://singularityhub.github.io/.github

And it will redirect, thus showing that GitHub pages works for the special .github repo. Huzzah.

**Comment by vbatts** [comment]
But why does this make life easier?

**Comment by vsoch** [comment]
There are several interactions that (if GitHub knows about some code of conduct, contributing, etc.) it will show them to the user. Here is a quick example - given that there is a known code of conduct and contributing files, notice the "Helpful resources" in the bottom right:

![image](https://user-images.githubusercontent.com/814322/53835115-adfa9d80-3f5a-11e9-8400-b5cadaaa7565.png)

Those link directly to the content of the .github folder for the repository, and given that the repository doesn't have one (per report of the GitHub docs above) it would go to the organization level .github. Another example is when you are a new contributor, it will show you a pop up that says "Hey if this is your first time, read this link to contribute -> (same links).

I would suspect there are other interactions that guide the user to the docs, but those are the two I've encountered.

**Comment by vsoch** [comment]
It's essentially doing the same thing we are doing with org, but adding the extra helpers to link to the docs from the other repos for us.

**Comment by vsoch** [comment]
oup just was able to get a screen shot of the other example I mentioned above (new contributor)
![image](https://user-images.githubusercontent.com/814322/53845107-eeb3e000-3f75-11e9-871a-4c41f96fa4cd.png)

**Comment by vbatts** [comment]
On 05/03/19 15:39 -0800, Vanessasaurus wrote:
>oup just was able to get a screen shot of the other example I mentioned above (new contributor)

oh nice. Hrm. I personally feel that "github" mechanics are separate but
related to "organizational" stuffs.

**Comment by vsoch** [comment]
Would it hurt to define both then, and use them together (and catered for different things)? For example the .github repo could hold more .github protocol - pull request templates, and a contributing doc that is more of a checklist. This checklist would have reading the *full* contributing guide linked as one of the items, and this would be in the org repo. The one in the org repo would be a more verbose document.

**Comment by vbatts** [comment]
Changes, like to CoC would have to be done in duplicate and in lockstep...

**Comment by vsoch** [comment]
That sounds like a bad idea. My thinking is that we wouldn't have a CoC in the .github repo, just the contributing doc with limited steps to take to contribute (that doesn't overlap much with the one in the org repo).
